# Generated by Django 6.1 on 2026-09-13 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='products.class', verbose_name='Группа категории'),
            preserve_default=False,
        ),
    ]
